In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
rand_mask_avg_err = pd.read_csv('recons_average_mse_per_precision_random_mask.csv',header=None)
# rand_mask_avg_err = rand_mask_avg_err.iloc[:,2].to_list()
grad_mask_avg_err = pd.read_csv('recons_average_mse_per_precision_gradual_mask.csv',header=None)

In [4]:
rand_mask_avg_err

       0              1         2
0    0.0  1738859053995  0.016802
1    1.0  1738859395543  0.027955
2    2.0  1738859728379  0.040872
3    3.0  1738860081247  0.055440
4    4.0  1738860434594  0.071551
5    5.0  1738860813450  0.089093
6    6.0  1738861209587  0.108381
7    7.0  1738861600109  0.129907
8    8.0  1738861979654  0.150620
9    9.0  1738862390800  0.172848
10  10.0  1738862808583  0.203180
11  11.0  1738863246368  0.252600

In [5]:
plt.plot(rand_mask_avg_err.iloc[:,0], rand_mask_avg_err.iloc[:,2], marker='o', linestyle='-', color='orange', label='Rndom Masking Reconstruction Error')
plt.plot(grad_mask_avg_err.iloc[:,0], grad_mask_avg_err.iloc[:,2], marker='o', linestyle='-', color='yellow', label='Gradual Masking Reconstruction Error')
plt.xlabel('Mask Percentage')
plt.ylabel('Error Rate')
plt.title('Error vs Mask Percentage')
plt.legend()
plt.grid(True)
# plot_path = 'recons/random/reconstruction_error_vs_mask_percentage.png'
plt.savefig('reconstruction_error_vs_mask_percentage.png')
plt.close()

In [6]:
rand_mask_avg_class_err = pd.read_csv('recons_average_classification_accuracy_random.csv',header=None) #'recons_average_cross_entropy_error_random_mask.csv'
grad_mask_avg_class_err = pd.read_csv('recons_average_classification_accuracy_gradual.csv',header=None) #'recons_average_cross_entropy_error_grad_mask.csv'

In [7]:
mask_percentages = np.arange(0.1, 1.1, 0.1)
mask_percentages = np.append(mask_percentages,[.85,.95])
mask_percentages = np.sort(mask_percentages)*100
rand_mask_avg_class_err.iloc[:,0] = mask_percentages
grad_mask_avg_class_err.iloc[:,0] = mask_percentages

In [19]:
rand_mask_avg_class_err

        0              1      2
0    10.0  1733127790662  0.000
1    20.0  1733127803375  0.000
2    30.0  1733127816078  0.000
3    40.0  1733127829036  0.000
4    50.0  1733127842251  0.002
5    60.0  1733127855632  0.002
6    70.0  1733127869328  0.002
7    80.0  1733127883048  0.004
8    85.0  1733127896811  0.004
9    90.0  1733127910852  0.010
10   95.0  1733127924983  0.026
11  100.0  1733127938820  0.002

In [8]:
plt.plot(rand_mask_avg_class_err.iloc[:,0], rand_mask_avg_class_err.iloc[:,2]*100, marker='o', linestyle='-', color='orange', label='Rndom Masking Reconstruction Error')
plt.plot(grad_mask_avg_class_err.iloc[:,0], grad_mask_avg_class_err.iloc[:,2]*100, marker='o', linestyle='-', color='yellow', label='Gradual Masking Reconstruction Error')
plt.xlabel('Mask Percentage')
plt.ylabel('Error Percentage')
plt.title('Error vs Mask Percentage')
plt.legend()
plt.grid(True)
# plt.show()
plt.savefig('Classification_error_vs_mask_percentage.png')
plt.close()

In [15]:
1 - 495/500

0.010000000000000009